### ISSUE TITLE
'Repository' object has no attribute 'get_file_contents' in 1.43.8

### ISSUE THREAD

**Issue by chanukov** [PyGithub/PyGithub#1222]
The following code works with 1.43.7 and fails on 1.43.8.
GitRepo is our Repo which was initialized elsewhere.
blob_sha = self.git_repo.get_file_contents(self.sf_config_file, "master").sha
results in 15:49:03  AttributeError: 'Repository' object has no attribute 'get_file_contents'

**Comment by s-t-e-v-e-n-k** [comment]
The method is now called get_contents(). Sorry, this probably should not have been changed in a point release.

**Comment by chanukov** [comment]
Can such breaking changes please get a bullet point in the docs in future.
https://github.com/PyGithub/PyGithub/pull/1223
