### ISSUE TITLE
README.md and PyPi link to latest docs with unreleased API

### ISSUE THREAD

**Issue by chrowe** [PyGithub/PyGithub#2550]
* macOS Ventura 13.3 (Apple M1 Chip)
* Conda installed by Homebrew
```
conda install pip
pip install PyGithub
```
* PyGithub           1.58.2
* `from github import Github` works fine but `from github import Auth` fails.

```
❯ conda activate utils
/opt/homebrew/Caskroom/miniconda/base/envs/utils/bin/python
❯ /opt/homebrew/Caskroom/miniconda/base/envs/utils/bin/python
Python 3.11.3 | packaged by conda-forge | (main, Apr  6 2023, 08:58:31) [Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from github import Github
>>> from github import Auth
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'Auth' from 'github' (/opt/homebrew/Caskroom/miniconda/base/envs/utils/lib/python3.11/site-packages/github/__init__.py)
```

**Comment by chrowe** [comment]
Ok, it looks like this was a change introduced in https://github.com/PyGithub/PyGithub/commit/fc2d0e150a53d90209b8f251ce686858449f12d0 so the docs in https://github.com/PyGithub/PyGithub/blob/master/README.md and on https://pygithub.readthedocs.io/en/latest/ are for that. I wonder if it is work defaulting to https://pygithub.readthedocs.io/en/stable/ for the docs site so it will match the current release?

**Comment by 8mnl** [comment]
Thanks for the links, @chrowe. Docs should definitely link to the stable version, as it's the one that is downloaded with pip.

For anyone getting the same error, authentication is currently still done in the instance:
`g = Github(login_or_token="access_token")`

without the need of 
`from github import Auth`

**Comment by lukech** [comment]
As a first-time user, it's really confusing to run into the import error by following the example in readme/documentation. Is there a plan to cut a new release to fix that (by including fc2d0e150a53d90209b8f251ce686858449f12d0 and making readme/doc consistent)? It looks like 5.18.2 was cut on the `release_v1_58` branch where the commit did not actually land.

**Comment by EnricoMi** [comment]
A new release is imminent.

**Comment by EnricoMi** [comment]
Technically, the link from `README.md` in the `master` branch should point to `latest`, because that is what `master` is.

Practically, the `README.md` in the `master` is the landing page for the project, so people will look for documentation there. Same holds for the PyPi page. Those pages should at least point to stable, ideally to the respective version.

**Comment by EnricoMi** [comment]
Fixed in master, will be mixed on PyPi with next release.

**Comment by lukech** [comment]
@EnricoMi thanks for fixing up the docs. Is there a rough estimate of when the next release is planned? I'd like to set a PyGithub version with the `Auth` module (the latest 5.18.2 does not have it) in my project's pyproject.toml. Don't hope to fall back to the legacy auth approach as I believe adopting the new `Auth` module will be the future.

**Comment by EnricoMi** [comment]
Maybe tomorrow.

**Comment by EnricoMi** [comment]
This has been released. Stable readthedocs to be published.

**Comment by chrowe** [comment]
How to the stable readthedocs get published? When I go to https://pygithub.readthedocs.io/ it redirects me to https://pygithub.readthedocs.io/en/latest/

**Comment by EnricoMi** [comment]
Maybe that is a setting with readthedocs, let me check with the owners if that can redirect to https://pygithub.readthedocs.io/en/stable/.
